### ISSUE TITLE
Snowmen do not respawn

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/Winter#42]
Hejo,
I have configured the following settings in the config:
```
Snowman:
  Disable_Melt_Damage: true
  Prevent_Target: true
  Damage:
    Snowball: 6.0
  Transform:
    Enabled: true
    Chance_Percent: 45
    Applicable:
    - ZOMBIE
```
The snowmen spawn and work, but they don't despawn. As soon as you have collected 1000 snowmen, the TPS start to drop. Of course there are manual ways to get rid of them, e.g. with /mv purge, but the situation is anything but optimal. Hopefully you are able to fix that issue.

PaperSpigiot 1.12.2 #1593
Winter: 1.5.5
Multiverse-Core: 2.5.0-b727
