### ISSUE TITLE
1.17.1: Blacklist issue

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/Winter#60]
```
    Regions:

      Enabled: true
      List:
      - '@blacklist'
      - '*'
```
I expect to have snow generation being disabled in all regions, but it still generates in them.

UPD:
Actually noticed one more issue. When regions support is enabled `@blacklist` restricts snow generation in individual selected regions, but is not generated in wilderess!
